/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dormitory;

import java.sql.Connection;

public class MainDashboard extends javax.swing.JFrame {

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
        
        
        Connection conn = DatabaseConnection.getConnection();
        if (conn == null) {
            System.out.println("Error: Could not connect to the database!");
        } else {
            System.out.println("Connected to Database!");

            // Fetch owner by username (Example: "admin")
            DatabaseConnection.getOwnerByUsername("admin");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LedgerButton = new javax.swing.JButton();
        ManageDorm = new javax.swing.JButton();
        ManageRoomButton = new javax.swing.JButton();
        ManageRentersButton = new javax.swing.JButton();
        NoticesButton = new javax.swing.JButton();
        PaymentsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setText("MIYAGI DORMITORY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        LedgerButton.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        LedgerButton.setText("Ledger");
        LedgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LedgerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LedgerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, 40));

        ManageDorm.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        ManageDorm.setText("Manage Dorm");
        ManageDorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDormActionPerformed(evt);
            }
        });
        jPanel1.add(ManageDorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 40));

        ManageRoomButton.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        ManageRoomButton.setText("Manage Room");
        ManageRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageRoomButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ManageRoomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, 40));

        ManageRentersButton.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        ManageRentersButton.setText("Manage Renters");
        ManageRentersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageRentersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ManageRentersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 120, 40));

        NoticesButton.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        NoticesButton.setText("Notices");
        NoticesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoticesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(NoticesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 120, 40));

        PaymentsButton.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        PaymentsButton.setText("Payments");
        PaymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PaymentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageDormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDormActionPerformed
        ManageDorm manageDormWindow = new ManageDorm();
        manageDormWindow.setVisible(true);
    }//GEN-LAST:event_ManageDormActionPerformed

    private void ManageRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRoomButtonActionPerformed
        ManageRoom manageRoomWindow = new ManageRoom();
        manageRoomWindow.setVisible(true);
    }//GEN-LAST:event_ManageRoomButtonActionPerformed

    private void ManageRentersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRentersButtonActionPerformed
        ManageRenters manageRentersWindow = new ManageRenters();
        manageRentersWindow.setVisible(true);
    }//GEN-LAST:event_ManageRentersButtonActionPerformed

    private void PaymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentsButtonActionPerformed
        Payments paymentsWindow = new Payments();
        paymentsWindow.setVisible(true);
    }//GEN-LAST:event_PaymentsButtonActionPerformed

    private void LedgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LedgerButtonActionPerformed
        Ledger ledgerFrame = new Ledger();
        ledgerFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LedgerButtonActionPerformed

    private void NoticesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoticesButtonActionPerformed
        Notices noticesWindow = new Notices();
        noticesWindow.setVisible(true);
    }//GEN-LAST:event_NoticesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LedgerButton;
    private javax.swing.JButton ManageDorm;
    private javax.swing.JButton ManageRentersButton;
    private javax.swing.JButton ManageRoomButton;
    private javax.swing.JButton NoticesButton;
    private javax.swing.JButton PaymentsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
