/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dormitory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class ManageDorm extends javax.swing.JFrame {

    /**
     * Creates new form ManageDorm
     */
    public ManageDorm() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        loadDorms();
    }

    private void loadDorms() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing table data

        try {
            // Database connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitory_db", "root", ""); 
            String sql = "SELECT dorm_id, dorm_name, owner_id, location FROM dorm"; // Added location to the SELECT query
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int dormID = rs.getInt("dorm_id");
                String dormName = rs.getString("dorm_name");
                int ownerID = rs.getInt("owner_id");
                String location = rs.getString("location"); // Fetch location from the result set

                model.addRow(new Object[]{dormID, dormName, ownerID, location}); // Include location in the table data
            }

            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RemoveDormButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        AddDormButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setText("MIYAGI DORMITORY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jTable1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dorm ID", "Dorm Name", "Owner", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 480, 250));

        RemoveDormButton.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        RemoveDormButton.setText("Remove Dorm");
        RemoveDormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveDormButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RemoveDormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 120, 30));

        BackButton.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 340, 120, 30));

        AddDormButton1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        AddDormButton1.setText("Add Dorm");
        AddDormButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDormButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(AddDormButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new MainDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddDormButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDormButton1ActionPerformed
        AddDorm addDormFrame = new AddDorm();
    
        // Add a window listener to detect when the AddDorm frame is closed
        addDormFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadDorms();
            }
        });

        addDormFrame.setVisible(true);
    }//GEN-LAST:event_AddDormButton1ActionPerformed

    private void RemoveDormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveDormButtonActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a dorm to remove.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get Dorm ID from selected row
        int dormID = (int) jTable1.getValueAt(selectedRow, 0);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this dorm?", "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Database connection
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitory_db", "root", "");

                // SQL DELETE statement
                String sql = "DELETE FROM dorm WHERE dorm_id = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, dormID);

                int deletedRows = pst.executeUpdate();

                if (deletedRows > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Dorm removed successfully.");
                    loadDorms(); // Refresh the table after deletion
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to remove dorm.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }

                con.close();
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_RemoveDormButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDorm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDorm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDorm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDorm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDorm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDormButton1;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton RemoveDormButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
